CXX=g++
CC=gcc
TESTPATH=.
INCLUDE=$(TESTPATH)
FLAGS=-m32 -I$(INCLUDE)
LIBS=-lpthread -lbinsem -lut -lgtest
LIBS_PATH=-L lib -L $(TESTPATH)

all: test_run
	./test_run

test_run: test_main.cpp
	$(CXX) $^ $(LIBS) $(LIBS_PATH) $(FLAGS) -o $@

clean:
	$(RM) test_run
